version: 2

sources:
  - name: gdelt
    database: gdelt-bq
    schema: gdeltv2
    tables:
      - name: events_partitioned
      - name: eventmentions_partitioned
      - name: domainsbycountry_alllangs_april2015